name: Java CI/CD with Docker & EC2 Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Calculate Current Version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
          tag_prefix: 'v'

      - name: Use Calculated Version
        run: echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest myapp:${{ steps.calculate-version.outputs.version-string }}

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.OFEK_DOCKERHUB_PSWRD }}" | docker login -u "${{ secrets.OFEK_DOCKERHUB }}" --password-stdin
          docker push myapp:${{ steps.calculate-version.outputs.version-string }}


      - name: Deploy to AWS EC2
        run: |
          echo "Deploying to EC2..."
          ssh -o StrictHostKeyChecking=no -i {{ secrets.AWS_EC2_KEY  }} ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            sudo docker pull myapp:${{ steps.calculate-version.outputs.version-string }}
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d -p 80:8080 --name myapp myapp:${{ steps.calculate-version.outputs.version-string }}
          EOF
