name: Java CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Calculate Version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
          tag_prefix: 'v'

      - name: Update Version Automatically
        run: echo "VERSION=${{ steps.calculate-version.outputs.version-string }}" >> $GITHUB_ENV
  
      - name: Extract Project Name and Version from pom.xml
        run: |
          echo 'Extracting project name from pom.xml...'
          PROJECT_NAME=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.name)
          echo "Project name: $PROJECT_NAME"

          echo 'Extracting project version from pom.xml...'
          PROJECT_VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          echo "Project version: $PROJECT_VERSION"

      - name: Run Java Application
        run: |
          echo "Running Java application..."
          java -jar target/${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.jar


      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ env.VERSION }} .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.OFEK_DOCKERHUB_PSWRD }}" | docker login -u "${{ secrets.OFEK_DOCKERHUB }}" --password-stdin
          docker tag myapp:${{ env.VERSION }} ${{ secrets.OFEK_DOCKERHUB }}/myapp:${{ env.VERSION }}
          docker push ${{ secrets.OFEK_DOCKERHUB }}/myapp:${{ env.VERSION }}
