name: Java CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Update Version Automatically
        run: |
          # Fetch the latest version from Git tags (fallback to 1.0.0 if no tags exist)
          LAST_VERSION=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v1.0.0")

          # Remove the "v" prefix
          LAST_VERSION=${LAST_VERSION#v}

          # Increment the patch version (X.Y.Z → X.Y.(Z+1))
          NEW_VERSION=$(echo $LAST_VERSION | awk -F. '{print $1"."$2"."$3+1}')

          # Create a new Git tag with the updated version
          git tag -a v$NEW_VERSION -m "Version $NEW_VERSION"
          git push origin v$NEW_VERSION

          echo "✅ Updated version to $NEW_VERSION"

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.OFEK_DOCKERHUB_PSWRD }}" | docker login -u "${{ secrets.OFEK_DOCKERHUB }}" --password-stdin
          docker tag myapp:latest ${{ secrets.OFEK_DOCKERHUB }}/myapp:latest
          docker push ${{ secrets.OFEK_DOCKERHUB }}/myapp:latest
