name: Java CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Update Version Automatically
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          LAST_VERSION=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v1.0.0")

          LAST_VERSION=${LAST_VERSION#v}

          NEW_VERSION=$(echo $LAST_VERSION | awk -F. '{print $1"."$2"."$3+1}')

          git tag -a v$NEW_VERSION -m "Version $NEW_VERSION"
          git push origin v$NEW_VERSION

          echo " Updated version to $NEW_VERSION"

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.OFEK_DOCKERHUB_PSWRD }}" | docker login -u "${{ secrets.OFEK_DOCKERHUB }}" --password-stdin
          docker tag myapp:latest ${{ secrets.OFEK_DOCKERHUB }}/myapp:latest
          docker push ${{ secrets.OFEK_DOCKERHUB }}/myapp:latest
